-- Atualizacao: certificados emitidos ao final dos cursos.

ALTER TABLE education_courses
    ADD COLUMN IF NOT EXISTS public_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER cover_image,
    ADD COLUMN IF NOT EXISTS certificate_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER public_enabled,
    ADD COLUMN IF NOT EXISTS certificate_title VARCHAR(180) NULL AFTER certificate_enabled,
    ADD COLUMN IF NOT EXISTS certificate_text TEXT NULL AFTER certificate_title,
    ADD COLUMN IF NOT EXISTS certificate_font_family VARCHAR(80) NULL AFTER certificate_text,
    ADD COLUMN IF NOT EXISTS certificate_background VARCHAR(255) NULL AFTER certificate_font_family,
    ADD COLUMN IF NOT EXISTS certificate_min_frequency TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER certificate_background,
    ADD COLUMN IF NOT EXISTS certificate_show_recipient TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_min_frequency,
    ADD COLUMN IF NOT EXISTS certificate_show_nature TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_recipient,
    ADD COLUMN IF NOT EXISTS certificate_show_modality TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_nature,
    ADD COLUMN IF NOT EXISTS certificate_show_period TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_modality,
    ADD COLUMN IF NOT EXISTS certificate_show_approval TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_period,
    ADD COLUMN IF NOT EXISTS certificate_show_institution TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_approval,
    ADD COLUMN IF NOT EXISTS certificate_show_meta TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_institution,
    ADD COLUMN IF NOT EXISTS certificate_show_legal TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_show_meta,
    ADD COLUMN IF NOT EXISTS certificate_course_nature VARCHAR(180) NULL AFTER certificate_show_legal,
    ADD COLUMN IF NOT EXISTS certificate_modality VARCHAR(80) NULL AFTER certificate_course_nature,
    ADD COLUMN IF NOT EXISTS certificate_approval_criteria VARCHAR(255) NULL AFTER certificate_modality,
    ADD COLUMN IF NOT EXISTS certificate_legal_text TEXT NULL AFTER certificate_approval_criteria,
    ADD COLUMN IF NOT EXISTS certificate_institution_name VARCHAR(180) NULL AFTER certificate_legal_text,
    ADD COLUMN IF NOT EXISTS certificate_institution_city VARCHAR(120) NULL AFTER certificate_institution_name,
    ADD COLUMN IF NOT EXISTS certificate_institution_cnpj VARCHAR(32) NULL AFTER certificate_institution_city,
    ADD COLUMN IF NOT EXISTS certificate_institution_site VARCHAR(180) NULL AFTER certificate_institution_cnpj,
    ADD COLUMN IF NOT EXISTS certificate_objectives TEXT NULL AFTER certificate_institution_site,
    ADD COLUMN IF NOT EXISTS certificate_competencies TEXT NULL AFTER certificate_objectives,
    ADD COLUMN IF NOT EXISTS certificate_responsible_name VARCHAR(180) NULL AFTER certificate_competencies,
    ADD COLUMN IF NOT EXISTS certificate_responsible_credential VARCHAR(180) NULL AFTER certificate_responsible_name,
    ADD COLUMN IF NOT EXISTS certificate_program_enabled TINYINT(1) NOT NULL DEFAULT 1 AFTER certificate_responsible_credential,
    ADD COLUMN IF NOT EXISTS certificate_program_background VARCHAR(255) NULL AFTER certificate_program_enabled,
    ADD COLUMN IF NOT EXISTS certificate_program_extra TEXT NULL AFTER certificate_program_background,
    ADD COLUMN IF NOT EXISTS certificate_program_columns TINYINT UNSIGNED NOT NULL DEFAULT 2 AFTER certificate_program_extra;

CREATE TABLE IF NOT EXISTS education_certificates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    course_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    person_id BIGINT UNSIGNED NULL,
    verification_code VARCHAR(48) NOT NULL,
    student_name VARCHAR(180) NULL,
    requested_student_name VARCHAR(180) NULL,
    name_change_status VARCHAR(20) NULL,
    name_change_requested_at DATETIME NULL,
    name_change_reviewed_by BIGINT UNSIGNED NULL,
    name_change_reviewed_at DATETIME NULL,
    issued_at DATETIME NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY uq_education_certificate_course_user (course_id, user_id),
    UNIQUE KEY uq_education_certificate_course_person (course_id, person_id),
    UNIQUE KEY uq_education_certificate_code (verification_code),
    CONSTRAINT fk_education_certificate_course FOREIGN KEY (course_id) REFERENCES education_courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_education_certificate_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_education_certificate_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
    CONSTRAINT fk_education_certificate_reviewer FOREIGN KEY (name_change_reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

ALTER TABLE education_certificates
    MODIFY COLUMN user_id BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS person_id BIGINT UNSIGNED NULL AFTER user_id,
    ADD COLUMN IF NOT EXISTS student_name VARCHAR(180) NULL AFTER verification_code,
    ADD COLUMN IF NOT EXISTS requested_student_name VARCHAR(180) NULL AFTER student_name,
    ADD COLUMN IF NOT EXISTS name_change_status VARCHAR(20) NULL AFTER requested_student_name,
    ADD COLUMN IF NOT EXISTS name_change_requested_at DATETIME NULL AFTER name_change_status,
    ADD COLUMN IF NOT EXISTS name_change_reviewed_by BIGINT UNSIGNED NULL AFTER name_change_requested_at,
    ADD COLUMN IF NOT EXISTS name_change_reviewed_at DATETIME NULL AFTER name_change_reviewed_by;
